- id: meson-fmt
  name: meson
  description: ''
  entry: meson format
  language: python
  files: ^(.*/)?(meson\.build|meson\.format|\.editorconfig)$

#- id: meson-format-fix
#  name: meson-format
#  description: ''
#  entry: meson format --inplace
#  language: python
#  'files': ^(.*/)?(meson\.build|meson\.format)$
#
#- id: meson-format-fix
#  name: meson-format
#  description: ''
#  entry: meson format --check-only
#  language: python
#  'files': ^(.*/)?(meson\.build|meson\.format)$
