-   id: meson-fmt
    name: meson
    description: ''
    entry: meson fmt
    language: python
    'files': ^(.*/)?(meson\.build)$
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
