[build-system]
requires = ["flit-core~=3.9"]
build-backend = "flit_core.buildapi"

[project]
name = "dummy-package"
version = "0"
description = "mirror for meson"
authors = []
license = { text = 'MIT' }

requires-python = "~=3.8"

dependencies = [
    'meson==1.9.1',
]
